version: "3.9"

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "3111:80"   # access at http://localhost:3111
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
